Fabric 1.20.4 update
hashalite/Freecam pull request #127
Opened 2023-12-15 15:23 UTC by tticehurst

Compiled well on Fabric. Disabled forge as it would not compile. 
Attempted troubleshoot but only have limited experience with forge over fabric.

2023-12-15 22:45 UTC, MattSturgeon requested changes
Spotted a couple things that can be improved.

Additionally, there's some changes that should be made to the root `build.gradle` to (mostly) fix the forge build:  
_(Feel free to reference [this branch](https://github.com/MattSturgeon/Freecam/blob/127-fixes/build.gradle))_

- `dev.architectury.loom` should be bumped to "1.4-SNAPSHOT" (line 3)
- line 20 should be replaced with (this fixes the forge mapping error):
```gradle
mappings loom.layered {
    mappings "net.fabricmc:yarn:${rootProject.yarn_mappings}:v2"
    mappings "dev.architectury:yarn-mappings-patch-forge:${rootProject.yarn_mappings_patch}"
}
```

Also `yarn_mappings_patch` should be set in `gradle.properties` ([maven](https://maven.architectury.dev/dev/architectury/yarn-mappings-patch-forge/)):
```
yarn_mappings_patch=1.20.4+build.1
```

The forge remapping error was caused by https://github.com/MinecraftForge/MinecraftForge/issues/9817, which Neoforge [fixed](https://github.com/MinecraftForge/MinecraftForge/issues/9817) and architectury added a mappings [patch](https://github.com/architectury/yarn-mappings-patch) to workaround.

@hashalite this kinda issue would be avoided by:  
a) targeting neoforge instead of lex and/or
b) using official mojmap instead of yarn. 

Even with that fix, there's still another issue with the forge build. It fails in the dev env because of how architectury plugin splits the build into two mods. Upstream have a [fix](https://github.com/Juuxel/union-relauncher/), but I haven't looked into it yet. It may work in production though (if so, forge could be re-enabled).

2023-12-15 22:45 UTC, MattSturgeon commented on gradle.properties
>  cloth_version=12.0.109
Bump these too:
```suggestion
modmenu_version=9.0.0-pre.1
cloth_version=13.0.114
```

2023-12-15 22:45 UTC, MattSturgeon commented on gradle.properties
> +fabric_version=0.91.2+1.20.4
Remove duplicate:
```suggestion
fabric_api_version=0.91.2+1.20.4
```

2023-12-15 22:45 UTC, MattSturgeon commented on gradle.properties
> +enabled_platforms=fabric
Maybe add a comment? 
```suggestion
enabled_platforms=fabric # Forge disabled for now
```

2023-12-15 22:45 UTC, MattSturgeon commented on settings.gradle
> +// include("forge")
I don't _think_ this is needed if `forge` is dropped from `enabled_platforms`?

2023-12-15 22:45 UTC, MattSturgeon commented on gradlew
Nit: This is adding `execute` file permission (guessing the file was previously committed on windows). This _probably_ should be a separate commit... @hashalite?

2023-12-15 22:45 UTC, MattSturgeon commented on gradle.properties
> +mod_version=1.2.1.2
Probably should leave the version number for @hashalite to bump on release.

2023-12-15 22:45 UTC, MattSturgeon commented on gradle.properties
> +architectury_version=11.0.8
:+1: If #129 gets merged this will conflict.

2023-12-15 22:45 UTC, MattSturgeon commented on common/src/main/java/net/xolt/freecam/config/CollisionWhitelist.java
> +            TransparentBlock.class,
`TransparentBlock` is extended by `GrateBlock`, `StainedGlassBlock`, & `TintedGlassBlock`.

Don't think we want `GrateBlock` in the whitelist (it's not fully transparent _enough_ that you should be able to no-clip through it), so should probably be:
```suggestion
            StainedGlassBlock.class,
            TintedGlassBlock.class,
```

This was probably already an issue, but the mapping change highlighted it.

2023-12-16 13:10 UTC, tticehurst commented on settings.gradle
> +// include("forge")
It still tried to build forge even if the enabled_platforms only had fabric

2023-12-16 13:11 UTC, tticehurst commented
Added changes suggested

2023-12-16 15:08 UTC, tticehurst commented
> Even with that fix, there's still another issue with the forge build. It fails in the dev env because of how architectury plugin splits the build into two mods. Upstream have a [fix](https://github.com/Juuxel/union-relauncher/), but I haven't looked into it yet. It may work in production though (if so, forge could be re-enabled).

Can confirm it works in production

2023-12-16 15:36 UTC, MattSturgeon requested changes
> Can confirm [forge] works in production

Brilliant! Hopefully @hashalite can get this merged/released soon then :tada: 

---

Other than a couple more nits-picks I think this is good to go, thanks!

2023-12-16 15:36 UTC, MattSturgeon commented on build.gradle
Should bump loom to `"1.4-SNAPSHOT"` (line 3) for better support of the newer versions:

![image](https://github.com/hashalite/Freecam/assets/5046562/c4190cf0-33f6-4058-b3e9-aec96b7a3f8d)

[Upstream changelog](https://github.com/FabricMC/fabric-loom/releases/tag/1.4)  
[Architectury discord](https://discord.gg/C2RdJDpRBP)

2023-12-16 15:36 UTC, MattSturgeon commented on gradle.properties
> +yarn_mappings_patch=1.20.4+build.1
nit: Personally I'd move this to line 6 so that it's next to `yarn_mappings`.

2023-12-16 15:41 UTC, tticehurst commented
Added nitpicks

2023-12-16 15:44 UTC, MattSturgeon approved these changes
Great. Personally, I'd squash all commits into one & then force-push, but idk how picky @hashalite is about keeping commit history clean.

I might post some build artifacts on #125 as idk how long it'll take for @hashalite to see/merge this...

2023-12-16 15:46 UTC, tticehurst commented
Will leave how the commits are for now until hashalite responds then will go from there, easier to squash than unsquash

2023-12-16 16:15 UTC, MattSturgeon commented
Here's a prod fabric build: [freecam-fabric-1.2.1.1-1.20.4.zip](https://github.com/hashalite/Freecam/files/13693114/freecam-fabric-1.2.1.1-1.20.4.zip)

For some reason the forge build is failing in prod with `Could not find net/minecraft/client/Minecraft.class in classloader`. Looks like the build isn't being remapped to searge mappings correctly? [freecam-forge-1.2.1.1-1.20.4.zip](https://github.com/hashalite/Freecam/files/13693120/freecam-forge-1.2.1.1-1.20.4.zip).

I haven't got time to look into this right now, it may or may not be 1.20.4 specific (could be a bug with #118)...

```
Launcher: standard

Java Arguments:
[-Xms2048m, -Xmx8064m, -Duser.language=en]


Minecraft process ID: 839


Checking: MERGED_MAPPINGS
Checking: MAPPINGS
Checking: MOJMAPS
Checking: PATCHED
Checking: MC_SRG
2023-12-16 16:06:20,459 main WARN Advanced terminal features are not available in this environment
[16:06:20] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, Bot_1, --version, 1.20.4, --gameDir, /home/matt/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/instances/freecam 1.20.4 forge test/.minecraft, --assetsDir, /home/matt/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/assets, --assetIndex, 12, --uuid, <PROFILE ID>, --accessToken, **********, --userType, offline, --versionType, release, --launchTarget, forge_client, --fml.forgeGroup, net.minecraftforge, --fml.forgeVersion, 49.0.9, --fml.mcVersion, 1.20.4, --width, 854, --height, 480]
[16:06:20] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: JVM identified as Flathub OpenJDK 64-Bit Server VM 17.0.9+7
[16:06:20] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 10.1.2 starting: java version 17.0.9 by Flathub; OS Linux arch amd64 version 6.6.3-1-default
[16:06:20] [main/INFO] [ne.mi.fm.lo.ImmediateWindowHandler/]: Loading ImmediateWindowProvider fmlearlywindow
[16:06:20] [main/INFO] [EARLYDISPLAY/]: Trying GL version 4.6
[16:06:20] [main/INFO] [EARLYDISPLAY/]: Requested GL version 4.6 got version 4.6
[16:06:20] [EarlyDisplay/INFO] [EARLYDISPLAY/]: GL info: AMD Radeon RX 5700 XT (navi10, LLVM 16.0.6, DRM 3.54, 6.6.3-1-default) GL version 4.6 (Core Profile) Mesa 23.2.1 (git-49a47f187e), AMD
[16:06:20] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=jar:file:///home/matt/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar!/ Service=ModLauncher Env=CLIENT
Exception caught from launcher
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:66)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.minecraftforge.bootstrap.Bootstrap.start(Bootstrap.java:48)
	at net.minecraftforge.bootstrap.ForgeBootstrap.main(ForgeBootstrap.java:18)
	... 8 more
Caused by: java.lang.IllegalStateException: Could not find net/minecraft/client/Minecraft.class in classloader SecureModuleClassLoader[SECURE-BOOTSTRAP]@102065302
	at SECURE-BOOTSTRAP/net.minecraftforge.fmlloader@1.20.4-49.0.9/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.getPathFromResource(CommonLaunchHandler.java:98)
	at SECURE-BOOTSTRAP/net.minecraftforge.fmlloader@1.20.4-49.0.9/net.minecraftforge.fml.loading.targets.ForgeProdLaunchHandler$Client.getMinecraftPaths(ForgeProdLaunchHandler.java:28)
	at SECURE-BOOTSTRAP/net.minecraftforge.fmlloader@1.20.4-49.0.9/net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator.scanMods(MinecraftLocator.java:24)
	at SECURE-BOOTSTRAP/net.minecraftforge.fmlloader@1.20.4-49.0.9/net.minecraftforge.fml.loading.moddiscovery.ModDiscoverer.discoverMods(ModDiscoverer.java:80)
	at SECURE-BOOTSTRAP/net.minecraftforge.fmlloader@1.20.4-49.0.9/net.minecraftforge.fml.loading.FMLLoader.beginModScan(FMLLoader.java:154)
	at SECURE-BOOTSTRAP/net.minecraftforge.fmlloader@1.20.4-49.0.9/net.minecraftforge.fml.loading.FMLServiceProvider.beginScanning(FMLServiceProvider.java:58)
	at SECURE-BOOTSTRAP/cpw.mods.modlauncher@10.1.2/cpw.mods.modlauncher.TransformationServiceDecorator.runScan(TransformationServiceDecorator.java:98)
	at SECURE-BOOTSTRAP/cpw.mods.modlauncher@10.1.2/cpw.mods.modlauncher.TransformationServicesHandler.lambda$runScanningTransformationServices$7(TransformationServicesHandler.java:96)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1779)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
	at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
	at SECURE-BOOTSTRAP/cpw.mods.modlauncher@10.1.2/cpw.mods.modlauncher.TransformationServicesHandler.runScanningTransformationServices(TransformationServicesHandler.java:98)
	at SECURE-BOOTSTRAP/cpw.mods.modlauncher@10.1.2/cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:49)
	at SECURE-BOOTSTRAP/cpw.mods.modlauncher@10.1.2/cpw.mods.modlauncher.Launcher.run(Launcher.java:86)
	at SECURE-BOOTSTRAP/cpw.mods.modlauncher@10.1.2/cpw.mods.modlauncher.Launcher.main(Launcher.java:73)
	at SECURE-BOOTSTRAP/cpw.mods.modlauncher@10.1.2/cpw.mods.modlauncher.BootstrapEntry.main(BootstrapEntry.java:17)
	at net.minecraftforge.bootstrap@2.0.0/net.minecraftforge.bootstrap.Bootstrap.moduleMain(Bootstrap.java:97)
	... 14 more
Exiting with ERROR
Process exited with code 2.
```

The only changes I've made are to the archive base: https://github.com/MattSturgeon/Freecam/commit/725ee5d9b1320a9ec3933ac46a385676ca1a42fa

2023-12-16 16:30 UTC, tticehurst commented
hmm I managed to load up mc with the forge build and it all worked fine

2023-12-16 17:20 UTC, MattSturgeon commented
Just installed the official launcher and tested again. Works fine there.

I wasn't hitting an issue with our build, rather LexForge has broken support for unofficial launchers: https://github.com/MinecraftForge/MinecraftForge/issues/9815

2023-12-19 07:37 UTC, hashalite commented
Hello, apologies for the delay in getting back to you. I have been quite busy with exams over the past couple weeks. Thanks for taking the time to update the mod! Don't worry about cleaning up the commit history, I'm not too picky about that. I just want to confirm the issue with the forge build is not on our end before merging. Has anyone had time to look into it further?

2023-12-19 14:57 UTC, MattSturgeon commented
> Hello, apologies for the delay in getting back to you. I have been quite busy with exams over the past couple weeks.

No worries, hopefully they went well 🤞

> I just want to confirm the issue with the forge build is not on our end before merging. Has anyone had time to look into it further?

I've not looked into it much yet. My understanding is there's two separate issues; one effecting the dev env and the other affecting unofficial launchers.

I suspect the dev env will be solved by an architectury-loom update or some workaround discussed in they're discord. This shouldn't block doing a release.

I believe the unofficial launcher issue has nothing to do with our mod, and (if it's not fixed by launchers yet) would be reproducible even without any mods installed.

Again, I haven't confirmed that yet.

2023-12-19 17:07 UTC, tticehurst commented
Tried installing forge on multimc, just met with an error when attempting to lanch even without any mods. Seems to be a forge related issue rather than a mod one

2023-12-24 02:54 UTC, MattSturgeon commented
@hashalite It'd be great to get this merged and/or get a 1.20.4 release out before xmas :grinning: :christmas_tree: 

I know I've created a bunch of merge conflicts in other PRs. Let me know if you'd like me to put a branch together with the current conflicts resolved.

2023-12-24 03:23 UTC, hashalite commented
> @hashalite It'd be great to get this merged and/or get a 1.20.4 release out before xmas 😀 🎄

Yup! That's my goal

> I know I've created a bunch of merge conflicts in other PRs. Let me know if you'd like me to put a branch together with the current conflicts resolved.

If it isn't too much trouble, this would be very helpful

2023-12-24 04:56 UTC, hashalite commented
> If it isn't too much trouble, this would be very helpful

Never mind, it was just a couple of changes

2023-12-24 04:57 UTC, merged

2023-12-24 04:57 UTC, hashalite commented
Thanks again you all!

2023-12-26 05:15 UTC, hashalite commented on common/src/main/java/net/xolt/freecam/config/CollisionWhitelist.java
> +            TransparentBlock.class,
@MattSturgeon This actually broke Ignore Transparent for plain glass blocks, it looks like TintedGlass is something else. 

> it's not fully transparent enough that you should be able to no-clip through it

We do include iron bars in the same category, which have a similar transparency level to grates. I think they could be included

2023-12-26 12:28 UTC, MattSturgeon commented on common/src/main/java/net/xolt/freecam/config/CollisionWhitelist.java
> +            TransparentBlock.class,
> This actually broke Ignore Transparent for plain glass blocks, it looks like TintedGlass is something else.

Interesting. Good catch. Perhaps yarn got the name wrong, wouldn't be the first time. Guess I should've tested.

> We do include iron bars in the same category

I'd forgotten about that.  
That's one of the limitations of `CollisionWhitelist` (currently) only using the class. IIRC iron bars and glass panes share the same class, the only way to tell them apart is block data.

Might look into using block id instead, maybe allowing the user to create their own whitelist/blacklist...